### ISSUE TITLE
String representation of classes that hold configuration values

### ISSUE THREAD

**Issue by jaimergp** [openforcefield/openff-evaluator#37]
Hello,

I am (slowly) getting to know the code behind `propertyestimator` by running the examples interactively in the notebook. During that journey, I am finding patterns relying on objects that could benefit from string representations (`__repr__()` and `__str__()`).

One example is `propertyestimator.backends.backends.ComputeResources`, which is the default option for the `resources_per_worker` keyword in `propertyestimator.backends.DaskLocalClusterBackend`. Without a string representation, the `help()/?` message for `DaskLocalClusterBackend` reads like this:

```
Init signature:
backends.DaskLocalClusterBackend(
    number_of_workers=1,
    resources_per_worker=<propertyestimator.backends.backends.ComputeResources object at 0x7f096b314dd8>,
)
Docstring:     
A property estimator backend which uses a dask `LocalCluster` to
run calculations.
Init docstring: Constructs a new DaskLocalClusterBackend
File:           ~/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/propertyestimator/backends/dask.py
Type:           type
Subclasses:     
```

, which is not very informative in terms of default options. If `ComputeResources` had string reprs, the message could be printed like this:

```
Init signature:
backends.DaskLocalClusterBackend(
    number_of_workers=1,
    resources_per_worker=<propertyestimator.backends.backends.ComputeResources object with number_of_threads=1, number_of_gpus=0, preferred_gpu_toolkit=None, _gpu_device_indices=None at 0x7f096ab3b9b0>,
)
[...]
```

Example implementation:

```python
class ComputeResourcesRepr(backends.ComputeResources):
    def __repr__(self):
        cfg = ', '.join([f'{k}: {v}' for k, v in self.__getstate__().items()])
        return f'<{self.__module__}.{self.__class__.__name__} with {cfg} at 0x{id(self):02x}>'
```

Maybe there are more examples where this could be helpful, but I have yet to find them :) Would you welcome these changes as a PR once we list all potentially applicable classes?

**Comment by SimonBoothroyd** [comment]
Thanks for the fantastic feedback! 

Because I've always developed, ran and stepped through all of my code and examples directly in an IDE (currently PyCharm) I've never really used the `str` and `repr` representations because the debugger gives a full object hierarchy - so this need and use for them is great to know about!

Absolutely a PR would be most welcome to fix up the many instances I've missed! I wonder if we could just use a simple mix-in with an implementation similar to your `ComputeResourcesRepr` to automate this cleanly in the bulk of cases?

**Comment by jaimergp** [comment]
> I wonder if we could just use a simple mix-in with an implementation similar to your ComputeResourcesRepr to automate this cleanly in the bulk of cases?

Given that `.__getstate__()` is implemented the same way across all involved instances (returns a dict with string-representable keys and values), I'd say that yes, a `Representable` class only implementing `__str__` and `__repr__` for mixins would be enough. It could even check for the existence of `__getstate__` and throw a warning otherwise, maybe?

**Comment by jaimergp** [comment]
I was wondering whether other projects rely on this mixin idea or not, and yep, it's common! Great, I didn't think of this possibility.

Some examples:
- [`EasyReprMixin`](https://gist.github.com/hangtwenty/8742916) by `hangtwenty`
- [More mixins in `textblob`](https://textblob.readthedocs.io/en/dev/_modules/textblob/mixins.html)

We could also use [`reprlib`](https://docs.python.org/3.4/library/reprlib.html?highlight), which I have just discovered. Man, the standard library is _vast_. From the docs:

> The reprlib module provides a means for producing object representations with limits on the size of the resulting strings. This is used in the Python debugger and may be useful in other contexts as well.

**Comment by SimonBoothroyd** [comment]
> I was wondering whether other projects rely on this mixin idea or not, and yep, it's common! Great, I didn't think of this possibility.
> 
> Some examples:
> 
> * [`EasyReprMixin`](https://gist.github.com/hangtwenty/8742916) by `hangtwenty`
> * [More mixins in `textblob`](https://textblob.readthedocs.io/en/dev/_modules/textblob/mixins.html)
> 
> We could also use [`reprlib`](https://docs.python.org/3.4/library/reprlib.html?highlight), which I have just discovered. Man, the standard library is _vast_. From the docs:
> 
> > The reprlib module provides a means for producing object representations with limits on the size of the resulting strings. This is used in the Python debugger and may be useful in other contexts as well.

That's good to hear! And it sounds like this should be pretty simple to add in which is great!

**Comment by jaimergp** [comment]
I have just found about [`__qualname__`](https://www.python.org/dev/peps/pep-3155/), which might be what we need here instead of manually concatenating `__module__`, `__class__.__name__` etc.

**Comment by SimonBoothroyd** [comment]
This will be automatically handled once #226 is closed as `pydantic` provides this for free by default.
