### ISSUE TITLE
RecursionError in LocalFileStorage

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-evaluator#380]
https://github.com/openforcefield/openff-evaluator/blob/64d74405c34555ed710b9540fea289131835b821/openff/evaluator/storage/localfile.py#L18-L21

This recursive call means the property is not really very helpful.

```python
>>> from openff.evaluator.storage import LocalFileStorage
>>> lfs = LocalFileStorage()
>>> lfs.root_directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lily/anaconda3/envs/polymetrizer/lib/python3.9/site-packages/openff/evaluator/storage/localfile.py", line 21, in root_directory
    return self.root_directory
  File "/Users/lily/anaconda3/envs/polymetrizer/lib/python3.9/site-packages/openff/evaluator/storage/localfile.py", line 21, in root_directory
    return self.root_directory
  File "/Users/lily/anaconda3/envs/polymetrizer/lib/python3.9/site-packages/openff/evaluator/storage/localfile.py", line 21, in root_directory
    return self.root_directory
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```
My suggestion would be to just not privatize attributes with getter/setters, as I think it adds burden to code maintenance and is liable to bugs such as the one reported here. (The actual attribute used is `_root_directory`.)

**Comment by SimonBoothroyd** [comment]
> My suggestion would be to just not privatize attributes with getter/setters, as I think it adds burden to code maintenance and is liable to bugs such as the one reported here. (The actual attribute used is _root_directory.)

This is a pretty common code pattern and gives a bit of safeguarding in case you later change the internal code to not be resilient to external changes of this variable - I think the main issue here is bad testing and not necessarily maintenance burden!

A PR containing the typo fix + test would be welcome 🙂

**Comment by lilyminium** [comment]
> This is a pretty common code pattern and gives a bit of safeguarding in case you later change the internal code

Sure, I suppose I am a fervent follower of YAGNI and think it's fairly easy to change an attribute to a managed property -- if anything, this kind of code encourages me to use the "private" attribute because the public one can't really be accessed -- but we all have different styles :-)

>  I think the main issue here is bad testing and not necessarily maintenance burden!

I think of needing to write and maintain additional tests as maintenance burden!
