### ISSUE TITLE
Behavio(u)r spelling

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-evaluator#381]
Having keywords of `behavior` and classes of `Behaviour` seem ripe for spelling-induced errors. I'd recommend going with Behavior, as most of the world programs in American.

(e.g. `merge_behavior=InequalityMergeBehaviour.LargestValue`)

**Comment by SimonBoothroyd** [comment]
In general the code tries to adopt American spellings, but being English, old habits die hard 😉 . PR's fixing any inconsistencies would be welcome!
