### ISSUE TITLE
Wrong time format for slurm backend

### ISSUE THREAD

**Issue by pavankum** [openforcefield/openff-evaluator#418]
the wallclock time defined [here](https://github.com/openforcefield/openff-evaluator/blob/18962755f7663c37430d2baffb6c9bd80bd0556c/openff/evaluator/backends/backends.py#L118-L121
) is wrong for slurm jobs, slurm takes it as `Minutes:Seconds`  instead of `Hours:Minutes`

**Comment by mattwthompson** [comment]
I think this is resolved as per https://github.com/openforcefield/openff-evaluator/pull/419#issuecomment-1036683317 - please re-open if not!
