### ISSUE TITLE
Tutorial 04 - Trainning 

### ISSUE THREAD

**Issue by Yu-Tang-Lin** [openforcefield/openff-evaluator#420]
When I run this "!ForceBalance optimize.in" to start training, it shows the following.

-----------------------------------------------------------------------------
Calculation started at 2022-02-02 11:40 AM
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/ylinb/anaconda3/envs/OpenFFCrystal/bin/ForceBalance.py", line 45, in Run_ForceBalance
    optimizer.Run()
  File "/home/ylinb/anaconda3/envs/OpenFFCrystal/lib/python3.8/site-packages/forcebalance/optimizer.py", line 322, in Run
    xk = self.OptTab[self.jobtype]()
KeyError: 'single'

-----------------------------------------------------------------------------

Is there a specific dependency I need to install? 
I follow the install instruction here
https://openff-evaluator.readthedocs.io/en/latest/install.html

**Comment by jeff231li** [comment]
@Yu-Tang-Lin it looks like ForceBalance does not understand "single" for the variable `jobtype` in the `optimize.in` file. This should be the default option for `jobtype`, what happens if you try commenting this out in the input file? The alternative (for a single-point calculation) is to set `jobtype` to `optimize` and set `maxstep` to 0.

**Comment by Yu-Tang-Lin** [comment]
@jeff231li 
Sorry, I am checking "optimize.in", Do you mean that comment out this one? (I found it is the most closed code that related to singe)

# (allcap) The job type, defaults to a **single**-point evaluation of objective function
jobtype optimize

**Comment by Yu-Tang-Lin** [comment]
> @Yu-Tang-Lin it looks like ForceBalance does not understand "single" for the variable `jobtype` in the `optimize.in` file. This should be the default option for `jobtype`, what happens if you try commenting this out in the input file? The alternative (for a single-point calculation) is to set `jobtype` to `optimize` and set `maxstep` to 0.

I also try maxstep = 0 in optimize.in, but it will show the same error message

**Comment by Yu-Tang-Lin** [comment]
6

> @Yu-Tang-Lin it looks like ForceBalance does not understand "single" for the variable `jobtype` in the `optimize.in` file. This should be the default option for `jobtype`, what happens if you try commenting this out in the input file? The alternative (for a single-point calculation) is to set `jobtype` to `optimize` and set `maxstep` to 0.

May you tell me what's your version for forcebalance in your environment? My forcebalance version is 1.9.2

**Comment by jeff231li** [comment]
I have version 1.9.2 installed in my environment. What does your `optimize.in` file look like?

**Comment by Yu-Tang-Lin** [comment]
Yes, I also have version1.9.2. The `optimize.in` is generated from code Tutorial 04.
`input_file_path = get_data_filename("tutorials/tutorial04/optimize.in")`


Here is my `optimize.in` which was generated from Tutorial 04.
[optimize.zip](https://github.com/openforcefield/openff-evaluator/files/7998148/optimize.zip)

**Comment by Yu-Tang-Lin** [comment]
Hi, @jeff231li 

I also try to modify in `forcebalance/optimizer.py` (Toolkit in forcebalance)

`xk = self.OptTab[self.jobtype]()`
It seems that it will extract the `jobtype optimize` in the `optimize.in`  
But it doesn't work.

I manually add `self.jobtype = 'optimize'` in `forcebalance/optimizer.py`
The error message becomes to this. I guess there is some issue in the toolkit in forcebalance for recognizing the `jobtype `

`  File "/home/ylinb/anaconda3/envs/OpenFFCrystal/lib/python3.8/site-packages/forcebalance/optimizer.py", line 325, in Run
    xk = self.OptTab[self.jobtype]()
KeyError: 'optimize'`

Here is my optimize.err 
[optimize.txt](https://github.com/openforcefield/openff-evaluator/files/8019272/optimize.txt)

Let me know if you need any other info, we can test it together.

**Comment by jeff231li** [comment]
I'm not sure why it's giving you this error. This python [script](https://github.com/openforcefield/openff-evaluator/files/8027341/tutorials.zip) works for me, run the file with this command `python run_evaluator.py | tee console_output.log`. The problem could be how you installed your `conda` environment. Can you send the YAML file of your conda environment: `conda env export > environment.yaml`.

**Comment by Yu-Tang-Lin** [comment]
Hi Jeffry,

It's my environment.yaml
Thank you for helping me!

Sincerely,

Yu-Tang

**Comment by Yu-Tang-Lin** [comment]
Hi @jeff231li,

I follow #414 in the previous issue and use v0.3.9 to test Turorial. It can work. I guess there is an update between v0.3.9 and master.

Thank you for your help!

**Comment by mattwthompson** [comment]
I think this has fallen out of date - please do let us know if you run into new issues.
