### ISSUE TITLE
Solvation Free Energy calculations can generate lots of checkpoint data

### ISSUE THREAD

**Issue by ocmadin** [openforcefield/openff-evaluator#422]
I'm currently running a large set of solvation free energies with Evaluator, and it's generated a larger-than-expected amount of data (3.7T so far for 380 SFEs), which is mainly due to large (up to 30GB) solvent checkpoint `solvent*_checkpoint.nc` files (in the `working-directory/SimulationLayer/request_name/*_conditional_group/*_run_yank` folder. I *think* these checkpoint files can be deleted after each individual calculation finishes, but currently they are not deleted until the entire set of calculations finishes, so users running a large number of calculations could wind up with a problematic amount of intermediate data if they aren't aware.  

Is it possible to clean up these checkpoint files after each individual calculation finishes?

**Comment by SimonBoothroyd** [comment]
@ocmadin these files should be deleted once the calculations are finished - which version of evaluator are you using? 

When you are setting up the `EvaluatorServer`, I'd recommend setting:

```
EvaluatorServer(..., enable_data_caching=False, delete_working_files=True)
```

to ensure data isn't cached and the checkpoint files are deleted.

**Comment by ocmadin** [comment]
This is on Evaluator 0.3.4.  I think I've found the issue, though - the `server-config.json` file that nonbonded creates doesn't include an argument for `delete_working_files=True` or `enable_data_caching=False`.  IIRC `delete_working_files=True` by default so maybe it's the data caching that's the problem?  Either way I think what needs to be modified is the `_generate` method of the `BenchmarkInputFactory` class (lines 93-162): https://github.com/SimonBoothroyd/nonbonded/blob/master/nonbonded/library/factories/inputs/benchmark.py

**Comment by ocmadin** [comment]
Also want to note that I was talking to @jchodera and his thought is that having `checkpoint_interval=1` (https://github.com/openforcefield/openff-evaluator/blob/6e6f0a47e1157f8f4b2971b5071c11f2e0291092/openff/evaluator/protocols/yank.py#L91-L95) for YANK is much too low and is causing a slowdown as well as high data generation (he suggested `checkpoint_interval=10` would be faster/cheaper).  Do you know if this was intentionally set to 1 or if it's just a default value that might need to be changed?

**Comment by SimonBoothroyd** [comment]
Ooh the other thing you will want to do is make sure `batch_mode` is set to `SameComponents` in `estimation-options.json`. 

Normally you'd want this to remain as the default `SharedComponents` so that redundant simulations can be removed, but in the case of solvation free energies there are no redundant calculations to remove and what usually happens is all calculations end up in the same batch, and so the working files aren't deleted until the full set of calculations are finished.

**Comment by SimonBoothroyd** [comment]
> Do you know if this was intentionally set to 1 or if it's just a default value that might need to be changed? 

I thought I'd used settings recommended by Andrea at the time, but it's possible these defaults might need tweaking in the future.

**Comment by ocmadin** [comment]
> Ooh the other thing you will want to do is make sure `batch_mode` is set to `SameComponents` in `estimation-options.json`.
> 
> Normally you'd want this to remain as the default `SharedComponents` so that redundant simulations can be removed, but in the case of solvation free energies there are no redundant calculations to remove and what usually happens is all calculations end up in the same batch, and so the working files aren't deleted until the full set of calculations are finished.

Ahhhhhhh, this sounds like the issue, in combination with the low checkpoint interval making these working files quite large.  I just checked and it's set to `SharedComponents` here.  I'll update that manually when I run these in the future, is there an easy way to modify the setup script (https://github.com/openforcefield/openff-sage/blob/325460b254c3532b96ae43deb5a3a963605609b6/scripts/setup-g-solv-benchmarks.py#L75) so that it sets `batch_mode=SameComponents`?

**Comment by ocmadin** [comment]
After setting `checkpoint_value=10`, I get the following error: 
```
        if self.checkpoint_interval != 1:
            raise ValueError(
                "The checkpoint interval must currently be set to one due to a bug in "
                "how YANK extracts trajectories from checkpoint files."
            )
```
Which is described here:
https://github.com/openforcefield/openff-evaluator/blob/master/openff/evaluator/protocols/yank.py#L632-L636

@SimonBoothroyd, do you remember anything about the nature of this bug?  I can't find a corresponding issue in `yank`.

**Comment by ocmadin** [comment]
@mattwthompson @SimonBoothroyd is this something that you could look into? Not super urgent, but it makes SFE calculations with Evaluator slow and data-intensive.  Happy to help in any way I can!

(Tagging @jchodera as well since this is an interaction between `yank` and Evaluator)

**Comment by mattwthompson** [comment]
I've added it to our trello board; probably not going to be able to dig into it myself soon but it's documented.

It seems like the first thing to do is dig up the history of this Yank bug. If it's lost to the sands of time, I wonder if checkpointing every timestep is still necessary?

**Comment by ocmadin** [comment]
Necessary as in "if we allowed users to choose a different checkpoint frequency, would the evaluator calculation break?"

**Comment by mattwthompson** [comment]
Something like that; more or less "what would happen if this ValueError was removed?" I'm not sure this history here so Simon would probably be best equipped to answer.

**Comment by ocmadin** [comment]
Okay, we're on the same page here.  I asked Simon about this a while back and he didn't remember what the bug was, maybe one of the yank developers would recognize it?

>"what would happen if this ValueError was removed?"

I can test this out sometime in the next couple days
