### ISSUE TITLE
Unable to install openff-evaluator on windows 11

### ISSUE THREAD

**Issue by matzegltg** [openforcefield/openff-evaluator#444]
Hi,

I'm unable to install the openff-evaluator module on my windows 11 64x desktop PC.

I created a new conda env called "openff-evaluator", tried downloading openff-evaluator and got this result.

![grafik](https://user-images.githubusercontent.com/62802204/165046253-b397dde3-4931-46f8-b4e6-e559d2c6d981.png)

I also tried downloading it from source but got the same results.

Is this a known issue?

Regards

**Comment by mattwthompson** [comment]
Hi @matzegltg, in general, our software stack is not available on (native) Windows. We don't go out of our way to prevent it from working, but we don't test on it and some of our dependencies happen to not be available. I'm not sure which package is missing in this case - you're running the right commands but `conda` unfortunately does not provide the right feedback. (There's usually something besides blank lines under "`UnsatisfiableError` ...") The quickest path to getting something up and running would be switching over to WSL2, a Linux VM, or a separate Linux/macOS workstation. Evaluator should be one-step installable on those platforms.
