### ISSUE TITLE
tutorial data and script are outdated

### ISSUE THREAD

**Issue by wenyan4work** [openforcefield/openff-evaluator#480]
1. the example data are outdated. For example, `https://github.com/openforcefield/openff-evaluator/blob/1e1a2d06e5a01d0f3262518a648996314fdb8276/openff/evaluator/data/tutorials/tutorial02/estimated_data_set.json#L241` here `openff.evaluator.utils.statistics` no longer exists
2. `https://github.com/openforcefield/openff-evaluator/blob/main/docs/tutorials/tutorial04.ipynb` this script uses some old api of `openff-evaluator` and `openff-toolkit` and no longer works.

**Comment by mattwthompson** [comment]
I believe this is closed with #499 and a release, please re-open if it hasn't been resolved
