### ISSUE TITLE
OE_LICENSE

### ISSUE THREAD

**Issue by faranak1991** [openforcefield/openff-evaluator#516]
Hi All,

Does the following license warning have an impact on the work?

Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.
LICENSE: Could not open license file specified by OE_LICENSE environment variable "/home/USERNAME/oe_license.txt"
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!

**Comment by mattwthompson** [comment]
This

> Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate. The estimate presumes the use of many statistically independent samples. Tests should be performed to assess whether this condition is satisfied. Be cautious in the interpretation of the data.


is emitted from `pymbar`; if you're using it there's [plenty to read up on](https://pymbar.readthedocs.io/en/master/)

This

> LICENSE: Could not open license file specified by OE_LICENSE environment variable "/home/USERNAME/oe_license.txt"
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!

is emitted by checks for an [OpenEye](https://www.eyesopen.com/oechem-tk) [license](https://www.openeye.net/support/license-agreements), which is commercial but typically made available for free to academics; nothing in OpenFF requires it, but it can be more performant than the open source alternatives (RDKit, AmberTools, etc.)

**Comment by faranak1991** [comment]
Hi @mattwthompson, 
Thanks for your quick answer. 
I'm trying to repeat tutorial02, but I'm facing an issue when trying to obtain the estimated properties. The error message "AttributeError: 'float' object has no attribute 'unit'" is came up. 

I attempted to assign values as Quantity objects with the correct units, but the problem persists. If you have any suggestions or recommendations, I would greatly appreciate your assistance.

**Comment by mattwthompson** [comment]
@faranak1991 please open a new issue
