### ISSUE TITLE
_PureOrMixtureData._smiles_to_molecular_weight gives incorrect MW

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-evaluator#568]
**Describe the bug**

Unfortunately this method does not return the MW for a single molecule but instead divides the MW by `unit.mole`, resulting in a per-mol weight that's scaled by Avogadro's number.

https://github.com/openforcefield/openff-evaluator/blob/c8c476ab6ec1e379049384ce23982e547d699f4b/openff/evaluator/datasets/thermoml/thermoml.py#L857-L859

This is the root cause of #553 -- while `_convert_mass_fractions` had units changed presumably to accomodate this, `_convert_molality` did not.

**Comment by mattwthompson** [comment]
Wow, so it's https://github.com/openforcefield/openff-units/issues/10 again?

**Comment by lilyminium** [comment]
Yup, looks like it:

```
import openmm.unit
from openff.units import unit

offkilo = 1 * unit.kilogram
ommkilo = 1 * openmm.unit.kilogram

offmass = 18 * unit.dalton
ommmass = 18 * openmm.unit.dalton

(offkilo / offmass).m_as(unit.dimensionless)
# [Out]: 3.345633756711735e+25

(ommkilo / ommmass).value_in_unit(openmm.unit.moles)
# [Out]: 55.55555555555555
```

**Comment by mattwthompson** [comment]
Working great
