### ISSUE TITLE
Weighting in excess properties done by ThermoML mole fractions rather than simulation mole fractions

### ISSUE THREAD

**Issue by mrshirts** [openforcefield/openff-evaluator#575]
**Describe the bug**

What we seem to be observing is that when you compute an excess property, and you do the calculation (for enthalpy for example), then with $H_{mixing} = <H_{mixture}>- (MF_0<H_0>-MF_1<H_1>$), the $MF_0$ and $MF_1$ are taken from ThermoML mole fractions, but it is more accurate to take them from the actually simulated mole fractions.  

In our case, the ThermoML mole fractions are 0.5098 and 0.4902, and the simulations ended up being done with 510 and 490 molecules, as that is what 509.8 and 490.2 get rounded to. 

In this case, one sees that if the molar enthalpy of component 0 is -44.879 and of component 1 is 251.418, and you get a mixture enthalpy 98.855, then if you use the simulation MF, you get (0.510)*(-44.879) + (0.490)\*251.418 - 98.855 = -1.45153, whereas if you use the ThermoML MF, you get (0.5098)\*(-44.879) + (0.4902)\*251.418 - 98.855 = -1.511, which a difference almost about 2x than the uncertainty; this -1.511 number is what Evaluator actually returned.  If the ThemoML MF had been, say 0.4904/0.5096, then you would have had a simulation of 1000 molecules still rounded to 490/510, and using the ThermoML MF would have been (0.5096)\*(-44.879) + (0.4904)\*251.418 - 98.855 = -1.57. 

I would argue that the most important thing is to use the mole fraction consistent with the mole fraction of the mixture solution actually simulated, as you want the ideal solution composition consistent with the mixture composition.  The H_mix(x) is not going to change very much when changing by x by 0.002, but mismatches result in larger errors.  More specifically, because the ideal components of the enthalpy are ~1-2 order of magnitude larger than the nonideal components, mismatching the ideal and nonideal solutions will give errors 1-2 orders of magnitude large than the changes in the nonideal contribution itself.  

**To Reproduce**

Any calculation should should work to show this error, but ones with smaller numbers of molecules so the rounding will give a larger difference.

**Output**

No error in output log per se. We figured this out by reproducing the calculation of enthalpy and figuring out mole fraction is being used.

**Computing environment (please complete the following information):**

I don't specifically recall the version of Evaluator - within the last 6 months.

**Additional context**

**Comment by lilyminium** [comment]
Definitely agree this is a problem and your proposed solution makes perfect sense, thanks so much for digging in and figuring out what was happening. (As a note to myself from quickly looking at the code, it looks like we need to construct a new Substance for the `WeightByMoleFraction` protocol that matches the simulation proportions -- I'll be able to spend more time on this when I'm back.) I don't think this part of the code has changed significantly over the past 6 months.

It sounds like you were working with a specific property -- would you be able to add it here? That would be a great test for fixing the issue.

**Comment by mrshirts** [comment]
@SimonBoothroyd is aware of this now as well and may be able to help.  He THOUGHT he had it set to use simulation mole fractions, but it didn't work as intended.  Barbara Morales in my group has the specific example we were using for molar enthalpy and she could add it - but I don't think she's added to the organization?  Let me see if I can do that.

**Comment by SimonBoothroyd** [comment]
Yeah we should be using the substance output when building the cords: https://github.com/openforcefield/openff-evaluator/blob/82ce709243435846532fddd14dcb76873eac52c7/openff/evaluator/protocols/coordinates.py#L86

**Comment by SimonBoothroyd** [comment]
I think 

https://github.com/openforcefield/openff-evaluator/blob/82ce709243435846532fddd14dcb76873eac52c7/openff/evaluator/properties/properties.py#L173

should instance reference 

`mixture_protocols.build_coordinates.output_substance`

**Comment by mrshirts** [comment]
@barmoral, looks like you are on now, you can add some files to reproduce things here.

**Comment by barmoral** [comment]
Hello all! Here I attach a zip file that contains the inputs and outputs I used to run the replicate test. Some details about the test:

- Molecule: OCCN(CCO)CCO (selected randomly)
- Force field used: Sage 2.1
- Water model: TIP3P-FB
- System size: 1000 molecules
- I focused on the mixture with mole fraction of 0.4902 for the solute and 0.5098 for the solvent/water. The id of this mixture assigned by evaluator is 6421.

As Michael mentioned, you will find the packmol output that states 0.49 and 0.51 were used to create the system. I have run replicates for the same test using system sizes of 1000 and 500 molecules, but at 2 ns. Let me know if these results might be useful as well, or if I can provide any other useful information. 


[1000_20ns.zip](https://github.com/user-attachments/files/17138686/1000_20ns.zip)

**Comment by lilyminium** [comment]
Thanks @barmoral, that's super helpful. I'm setting up some tests for this now and it'd be super helpful if you could also provide the working data for these if you saved the files, especially those associated with the `conditional_group` steps.

**Comment by barmoral** [comment]
Hi @lilyminium you can find those files in this [github repository](https://github.com/barmoral/evaluator-hmix-dens) under the label test_1000_longer_r#. These are my full results for the runs, excluding trajectory .dcd and .nc files which are really heavy. Let  me know if you'd need some of those to send them separately.

**Comment by lilyminium** [comment]
Thanks @barmoral, very much appreciated. Unfortunately to step through the process and create integration tests it'd be most helpful to have the `trajectory.dcd` files for the conditional group output, to avoid re-running the simulations. Just one of them would be great -- I've been using the `test_1000_longer_r1` files as a test case. We could possibly use Google Drive or similar to avoid GitHub's file size limits.
