### ISSUE TITLE
Use LangevinMiddleIntegrator for OpenMM simulations

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-evaluator#587]
**Is your feature request related to a problem? Please describe.**

Evaluator currently uses `openmmtools.integrators.LangevinIntegrator`. IMO we should probably be using the [LangevinMiddleIntegrator](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.LangevinMiddleIntegrator.html) which provides more accurate sampling. I also think I might have traced an odd issue where the integrator wasn't correctly regulating the temperature to 298K to the openmmtools one, which produces an average temperature of <290K; the openmm version correctly yields are temperature that fluctuates around ~300 K. (see attached screenshots).

Screenshots of properties correspond to:
* equilibration_statistics_openmmtools: `openmm.integrators.LangevinIntegrator`, v0.23.1
* equilibration_statistics_openmm: `openmm.openmm.LangevinIntegrator`, 8.1 version
* equilibration_statistics_middle: `openmm.openmm.LangevinMiddleIntegrator`, 8.2 version (in 8.2, LangevinIntegrator and LangevinMiddleIntegrator are the same)

**OpenMMTools, LangevinIntegrator**
![equilibration_statistics_openmmtools](https://github.com/user-attachments/assets/b69e5b5c-db9c-433c-8d72-aea108b33e37)

**OpenMM, LangevinIntegrator**
![equilibration_statistics_openmm](https://github.com/user-attachments/assets/158dec8f-c6c4-4bc4-86ae-9664a8124e92)
github.com/user-attachments/assets/cb614ab2-5cbf-467c-aba8-c94264a29141)

**OpenMM, LangevinMiddleIntegrator**
![equilibration_statistics_middle](https://github.com/user-attachments/assets/cf0d075c-bfb5-4849-a701-c1bbbea55b03)

**Comment by mrshirts** [comment]
Ouch! Yes, definitely should switch. The new KE looks right. You should check the distribution of the kinetic energy matches the correct Maxwell-Boltzmann distribution to within reasonable noise - https://github.com/shirtsgroup/physical_validation provides some quick tools to do this.

**Comment by mattwthompson** [comment]
Do the input arguments map on 1:1? I see something in inverse time that defaults to 1 inverse picosecond in each class, but they're named differently:

https://github.com/choderalab/openmmtools/blob/f3f355a3bc4dc18f5aff68f6ca7f0808ae18b138/openmmtools/integrators.py#L1072-L1080

http://docs.openmm.org/latest/api-python/generated/openmm.openmm.LangevinMiddleIntegrator.html#openmm.openmm.LangevinMiddleIntegrator

The other arguments look the same.

I double-checked to see which versions of OpenMM this requires, and it's supposed to be in there since 7.5. So no change there.

It'd be nice to remove the other `openmmtools` calls, but that's for a different day

**Comment by lilyminium** [comment]
Thanks for the suggestion @mrshirts! Seems to still be something going on here from a quick look. :/

Rep 1: p=0.026
Rep 2: p=0.005
Rep 3: p=0.037

In general the temperature seems higher than expected.

**Rep 1 (representative):**

```
After equilibration, decorrelation and tail pruning, 91.00% (910 frames) of original Kinetic energy remain.
Kinetic energy distribution check (non-strict)
Analytical distribution (T=298.15 K):
 * mu: 40233.47 kJ/mol
 * sigma: 315.81 kJ/mol
Trajectory:
 * mu: 40263.51 +- 10.86 kJ/mol
   T(mu) = 298.37 +- 0.08 K
 * sigma: 325.39 +- 13.19 kJ/mol
   T(sigma) = 307.19 +- 12.46 K

(2.7671927942605645, 0.7258647644155225)
```

**Comment by mrshirts** [comment]
I think this is _might_ be OK.  Note that T(sigma) is 307 +/- 12.46, so within error.   

We know that Langevin Middle integrator pushes a bit more of the error into the kinetic energy,  and the difference in T(mu) from 298.37 +/- 0.08 from 298.15  _might_ be about the order of magnitude error to expect.  And it is only 2 sigma off. 

Could you try running longer (maybe a factor or 4x) to make the statistics more precise, and then also do it with a shorter time step (1 fs instead of 2 fs), and see what the results are?  If everything snaps into place with 1 fs, that might provide some more info.  

While you are doing this, since we are interested in running some simulations with HMR, it might be good to do it with 2x a timestep and look at HMR as well.

**Comment by mattwthompson** [comment]
Just wanted to quickly note two things
1. The `openmmtools.integrators.LangevinIntegrator` -> `openmm.LangevinMiddleIntegrator` change is merged in but won't be in a release until this issue is resolved by stakeholders
1. Lily is on leave until about a week from today so turnaround might not be as quick as before

**Comment by lilyminium** [comment]
(Note: these simulations were run directly with Interchange and OpenMM, rather than using Evaluator machinery.)

## Using all "production" data

In general the 1 fs replicates do give a more reasonable distribution. In all cases T_mu, that is the temperature to which the estimated estimated mean corresponds, is higher than the target (298.15). T_sigma on the other hand doesn't show a unanimous directional bias. 

For the 1 fs simulations, only ~60% frames were kept (~6k frames) for analysis. For the 2 fs simulations, 80-90% the frames were kept (~4300 frames). For the 4 fs simulations, almost all frames were kept. Looking at the potential energy I was a bit doubtful as to whether it had actually equilibrated, so in the next section below are some results that only take the last 2000 frames.

**K-S p-values**

|Rep|   1fs, 10 ns, no HMR |   2fs, 10 ns, no HMR |   4fs, 8 ns, 3 amu HMR |
|---:|---------------------:|---------------------:|-----------------------:|
|  0 |          0.113475    |          7.82716e-06 |            1.64336e-21 |
|  1 |          0.0843738   |          1.27984e-09 |            2.70687e-17 |
|  2 |          0.0926494   |          4.67883e-08 |            7.2784e-22  |
|  3 |          0.000770994 |          1.85973e-08 |            6.48013e-25 |
|  4 |          0.000471407 |          8.95003e-08 |            1.70041e-19 |

**T_mu StDev, T_sigma StDevs**

|Rep| 1fs, 10 ns, no HMR                        | 2fs, 10 ns, no HMR                       | 4fs, 8 ns, 3 amu HMR                      |
|---:|:------------------------------------------|:-----------------------------------------|:------------------------------------------|
|  0 | (0.4947458713725119, 1.395081126473017)   | (3.487705286521891, 0.5930128654135989)  | (12.931012992509245, 0.25378179579708215) |
|  1 | (2.6191687567993593, 0.5369300648561859)  | (5.870027066808662, 0.9086732274843774)  | (11.324567807561822, 0.4392645559271541)  |
|  2 | (2.5121270447004442, 0.24042078210999143) | (7.955555805374661, 0.8697989016923292)  | (11.544713215371113, 0.8213482415527582)  |
|  3 | (3.518195799462769, 1.2435334515299423)   | (6.357323051656455, 0.710427375014919)   | (12.646443723689648, 0.8482578059899093)  |
|  4 | (3.33002115538814, 0.02498960293464943)   | (6.404566953710812, 0.47628218359503965) | (12.21325262739211, 0.3150083779270678)   |

## Using last 2000 frames

I truncated everything to the last 2k frames and allowed the library to still apply equilibration detection, decorrelation and tail pruning. Similar %s of frames were kept, ~55-70% for 1 fs, ~80-95% for 2 fs, nearly all for 4 fs.

**K-S p-values**
|    |   1fs, 10 ns, no HMR |   2fs, 10 ns, no HMR |   4fs, 8 ns, 3 amu HMR |
|---:|---------------------:|---------------------:|-----------------------:|
|  0 |            0.0422365 |          0.618605    |            1.64336e-21 |
|  1 |            0.637023  |          0.000606198 |            2.70687e-17 |
|  2 |            0.825876  |          0.00448659  |            7.2784e-22  |
|  3 |            0.458578  |          0.000536744 |            6.48013e-25 |
|  4 |            0.228979  |          4.69399e-05 |            1.70041e-19 |

**T_mu StDev, T_sigma StDevs**

|    | 1fs, 10 ns, no HMR                        | 2fs, 10 ns, no HMR                         | 4fs, 8 ns, 3 amu HMR                      |
|---:|:------------------------------------------|:-------------------------------------------|:------------------------------------------|
|  0 | (1.7803268618465957, 1.822536226614916)   | (0.34225005517071583, 0.37325713598291127) | (11.822335832417387, 0.26640207832500457) |
|  1 | (0.9783734523058691, 0.6934904284943091)  | (3.0646367598526663, 1.0848603319324106)   | (11.00905885135977, 0.41932342388118476)  |
|  2 | (0.7442088466990645, 0.2968213288078739)  | (4.350137497116118, 0.7140762802538337)    | (11.113264298454961, 0.8074381774324207)  |
|  3 | (0.6714012204713762, 0.20167293111504508) | (5.241876071776749, 1.4960334326931293)    | (12.568531025940938, 0.8396229573939281)  |
|  4 | (1.8612499500799886, 0.1424731761864196)  | (4.5702763707102765, 0.5041111605613413)   | (11.349660394967012, 0.29192449242445123) |

**Properties**

(representative replicates)

<img width="782" alt="Screenshot 2024-12-13 at 4 23 39 pm" src="https://github.com/user-attachments/assets/56feef52-ac82-4b22-8cc1-95fe66d1f027" />

**Comment by mrshirts** [comment]
Yeah, these are not really equilibrated yet, so it's hard to tell what is going on. 
Can you add the values of t_mu and t_sigma?

**Comment by lilyminium** [comment]
This is the same system Barbara's been using, 1000 mol of water + triethanolamine. I'm using Interchange to set up the box instead of Evaluator, although as of the most recent version it should yield similar results. 

I increased the equilibration to 10 ns and then took another 10 ns production data:

**traj T(mu)**
|    | 1fs, 10 ns, no HMR   | 2fs, 10 ns, no HMR   | 4fs, 10 ns, 3 amu HMR   | property   |
|---:|:---------------------|:---------------------|:------------------------|:-----------|
|  0 | 298.17 +- 0.03       | 298.38 +- 0.03       | 298.90 +- 0.05          | traj T(mu) |
|  1 | 298.22 +- 0.03       | 298.35 +- 0.04       | 298.89 +- 0.05          | traj T(mu) |
|  2 | 298.21 +- 0.03       | 298.39 +- 0.03       | 298.89 +- 0.05          | traj T(mu) |

**traj T(sigma)**
|    | 1fs, 10 ns, no HMR   | 2fs, 10 ns, no HMR   | 4fs, 10 ns, 3 amu HMR   | property      |
|---:|:---------------------|:---------------------|:------------------------|:--------------|
|  0 | 294.55 +- 2.62       | 300.87 +- 3.18       | 301.66 +- 4.61          | traj T(sigma) |
|  1 | 296.10 +- 2.87       | 305.15 +- 3.35       | 303.25 +- 4.05          | traj T(sigma) |
|  2 | 300.39 +- 2.82       | 297.28 +- 2.82       | 303.71 +- 4.00          | traj T(sigma) |

**n_frames kept out of 10k total**
|    |   1fs, 10 ns, no HMR |   2fs, 10 ns, no HMR |   4fs, 10 ns, 3 amu HMR | property   |
|---:|---------------------:|---------------------:|------------------------:|:-----------|
|  0 |                 6155 |                 4547 |                    2074 | n_frames   |
|  1 |                 5904 |                 4491 |                    2500 | n_frames   |
|  2 |                 6229 |                 4614 |                    2351 | n_frames   |

**K-S p**
|    |   1fs, 10 ns, no HMR |   2fs, 10 ns, no HMR |   4fs, 10 ns, 3 amu HMR | property   |
|---:|---------------------:|---------------------:|------------------------:|:-----------|
|  0 |            0.280068  |          5.19855e-08 |             5.58921e-31 | K-S p      |
|  1 |            0.0554076 |          1.9036e-05  |             3.44641e-37 | K-S p      |
|  2 |            0.0373843 |          5.54426e-07 |             1.58724e-38 | K-S p      |

Just checking I'm using physical_validation/Interchange correctly -- looking at the system and the code I don't believe Interchange writes out a CMMotionRemover as [OpenMM's createSystem does by default](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#removing-center-of-mass-motion)? So no center of mass motion is removed. Hence the number of degrees of freedom I have been using as input into the physical_validation package is simply (n_atoms x 3) - n_constraints (15 H-bond constraints for triethanolamine, 3 water constraints for TIP3P).

**Comment by mrshirts** [comment]
What we have been seeing is that triethanolamine seems to relax REALLY slowly, so I think that's what happened in the last simulations.  Smaller alchohols (I can't remember which one barbara looked at) relax much quicker to equilibrium.

It seems that after longer equilibration, things look mostly OK.  definintely looks fine for 1 fs, looks slightly off for 2fs, and definitely off for 4 fs.  Since LangevinMiddle is supposed to put more error into the kinetic energy, this is probably OK for 2 fs (at least within the errors of the length simulations we are running), but 4 fs should probably be investigated a bit more. 

Note that density and enthalpy of liquids is controlled almost completely by the average kinetic energy, fluctuations are not that important.

**Comment by mattwthompson** [comment]
>  I don't believe Interchange writes out a CMMotionRemover as [OpenMM's createSystem does by default](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#removing-center-of-mass-motion)

Correct on the first and I believe also the second part. Can easily swayed this should be changed (in a separate issue on the Interchange tracker, so as to not divert this discussion)

Also need to quickly say that I'm following this discussion but I'm not the person to make the call here (whether the call is "everything in the code is fine," any variant of "let's try x change ...", or something altogether different). I understand the original ask ("switch integrator?") to be resolved, so I'm not sure what the current goalpost is. That doesn't need to be clear right now, but I do need to make it explicit that I'm not in a position to determine it.

**Comment by lilyminium** [comment]
Thanks @mrshirts, that's useful to know, I'll chat to Barbara about whether triethanolamine is part of a small group of outliers or whether we need to re-evaluate the Evaluator defaults for equilibration times more (also opened an issue here: https://github.com/openforcefield/openff-evaluator/issues/591 )

Otherwise, as @mattwthompson points out we're moving away from the problem this issue was originally created to address. I agree that with #588 merged this issue has been resolved, and gives a better distribution for the 1 fs/2 fs timesteps. Let's move discussion of the 4 fs HMR issues to Slack for now since it's not clear that it's something to do with Evaluator at the moment. 

@mattwthompson I just opened an Interchange issue on the COM removal :-) https://github.com/openforcefield/openff-interchange/issues/1127

**Comment by mattwthompson** [comment]
Thanks for spelling out each of these threads - it helped me a lot to understand the specific ideas which are still open

I'm closing this for the reasons above; if we want to update the equilibration defaults, etc. let's continue that discussion there.
